import { ArrowDownRight, ArrowRight, CheckCircle, Sparkle, Warning } from "@phosphor-icons/react/dist/ssr";
import { WorkspaceLink } from "@/components/workspace-link";

export default function TodayPage() {
  return <div className="app-content"><header className="app-page-head"><div><span>Your operating day</span><h1>Good morning, Rakha.</h1><p>Three decisions need your attention. One may affect this week&apos;s revenue.</p></div><div className="app-head-actions"><WorkspaceLink className="button button-outline" href="/app/reports">Weekly review</WorkspaceLink></div></header><div className="app-grid"><div><section aria-labelledby="decisions-title"><div className="surface-head" style={{ border: 0, padding: 0, minHeight: 38 }}><h2 id="decisions-title">Decision inbox · 3</h2><WorkspaceLink href="/app/copilot">Ask why</WorkspaceLink></div><div className="decision-items"><Decision icon={<CheckCircle weight="fill" />} title="Approve Nabila for your final creator slot" meta="Approval needed · Ramadan Made Simple" description="87% match · Strong food storytelling and 2.8× historical ROAS." action="Review creator" href="/app/creators" /><Decision icon={<Warning weight="fill" />} title="One deliverable is 2 days overdue" meta="Delivery at risk · Weekend Family Feast" description="Dimas has not submitted the second TikTok draft. Publication is Friday." action="Resolve blocker" href="/app/campaigns" tone="warning" /><Decision icon={<ArrowDownRight weight="bold" />} title="ROAS declined 18% over the last 7 days" meta="Performance change · Lunch Box Launch" description="Conversion held steady, but paid amplification cost rose Rp 2.4m." action="See diagnosis" href="/app/copilot" tone="danger" /></div></section><section className="surface" style={{ marginTop: 20 }}><div className="surface-head"><h2>Performance pulse</h2><WorkspaceLink href="/app/reports">View evidence</WorkspaceLink></div><div className="metric-grid"><Metric label="Attributed revenue" value="Rp 86.4m" change="↑ 12.8%" /><Metric label="Campaign ROAS" value="3.42×" change="↓ 4.1%" /><Metric label="Active creators" value="18" change="↑ 3 this week" /><Metric label="On-time delivery" value="91%" change="↑ 6 pts" /></div></section></div><aside className="stack"><section className="surface"><div className="surface-head"><h2>Active campaigns</h2><WorkspaceLink href="/app/campaigns">View all</WorkspaceLink></div><div className="campaign-mini-list"><Campaign name="Ramadan Made Simple" meta="8 creators · Ends 16 Aug" progress="72%" /><Campaign name="Weekend Family Feast" meta="5 creators · Ends 9 Aug" progress="58%" warning /><Campaign name="Lunch Box Launch" meta="12 creators · Ends 28 Aug" progress="41%" /></div></section><section className="surface copilot-card"><Sparkle weight="fill" /><h3>Ask your business,<br />not your dashboard.</h3><p>Answers use governed metrics and always show the evidence.</p><WorkspaceLink href="/app/copilot"><span>Why did ROAS decline?</span><ArrowRight /></WorkspaceLink></section></aside></div></div>;
}

function Decision({ icon, title, meta, description, action, href, tone = "" }: { icon: React.ReactNode; title: string; meta: string; description: string; action: string; href: string; tone?: string }) { return <article className="decision-item"><span className={`decision-item-icon ${tone}`}>{icon}</span><div><small>{meta}</small><strong>{title}</strong><p>{description}</p></div><WorkspaceLink className="button button-outline" href={href}>{action}<ArrowRight /></WorkspaceLink></article>; }
function Metric({ label, value, change }: { label: string; value: string; change: string }) { return <div className="metric-box"><span>{label}</span><strong>{value}</strong><small>{change}</small></div>; }
function Campaign({ name, meta, progress, warning = false }: { name: string; meta: string; progress: string; warning?: boolean }) { return <div className="campaign-mini"><i className={warning ? "warning" : ""} /><div><strong>{name}</strong><span>{meta}</span></div><b>{progress}</b></div>; }
