"use client";

import { useState } from "react";
import { BookmarkSimple, CheckCircle, MapPin, PaperPlaneTilt, Sparkle, X } from "@phosphor-icons/react";
import { creatorOpportunities } from "@/lib/creator-intelligence-data";
export function CreatorOpportunities() {
  const [saved, setSaved] = useState<string[]>([]); const [applying, setApplying] = useState<(typeof creatorOpportunities)[number] | null>(null); const [notice, setNotice] = useState<string | null>(null);
  return <div className="app-content"><header className="app-page-head"><div><span>Matched opportunities</span><h1>Campaigns worth your time.</h1><p>Ranked by fit, not by who paid for placement. You decide where to apply.</p></div></header><section className="opportunity-grid">{creatorOpportunities.map(item => <article className="surface opportunity-card" key={item.id}><header><span className="opportunity-brand">{item.brand.slice(0, 2).toUpperCase()}</span><div><span>{item.brand}</span><h2>{item.title}</h2></div><button type="button" className={saved.includes(item.id) ? "saved" : ""} aria-label={`Save ${item.title}`} onClick={() => setSaved(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])}><BookmarkSimple weight={saved.includes(item.id) ? "fill" : "regular"} /></button></header><div className="opportunity-fit"><Sparkle weight="fill" /><span><strong>{item.fit}% match</strong>Food niche · Jakarta audience · delivery history</span></div><p>{item.deliverable}</p><div className="opportunity-meta"><span><MapPin /> Indonesia</span><span>Apply by {item.deadline}</span><strong>{item.budget}</strong></div><footer><span className="status-pill neutral">{item.status}</span><button className="button button-dark" type="button" onClick={() => setApplying(item)}>View & apply</button></footer></article>)}</section>{applying && <div className="dialog-backdrop" onMouseDown={() => setApplying(null)}><section className="dialog-card" role="dialog" aria-modal="true" aria-labelledby="apply-title" onMouseDown={event => event.stopPropagation()}><button className="dialog-close" type="button" onClick={() => setApplying(null)} aria-label="Close"><X /></button><span className="section-kicker">Creator application</span><h2 id="apply-title">{applying.title}</h2><form className="dialog-form" onSubmit={event => { event.preventDefault(); setApplying(null); setNotice("Application submitted. You can track it under Applications."); window.setTimeout(() => setNotice(null), 2600); }}><label className="field"><span>Your proposed rate</span><input required defaultValue="Rp9.500.000" /></label><label className="field"><span>Why are you a strong fit?</span><textarea required defaultValue="My audience regularly saves practical food content, and I can deliver a natural product story within the timeline." /></label><label className="field"><span>Relevant portfolio URL</span><input type="url" required defaultValue="https://tiktok.com/@nabilaeats" /></label><div className="dialog-actions"><button className="button button-outline" type="button" onClick={() => setApplying(null)}>Cancel</button><button className="button button-dark" type="submit"><PaperPlaneTilt /> Submit application</button></div></form></section></div>}{notice && <div className="toast"><CheckCircle weight="fill" />{notice}</div>}</div>;
}
