"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle, LinkSimple, Sparkle, UploadSimple } from "@phosphor-icons/react";

const steps = ["Identity", "Socials", "Portfolio", "Preferences", "Review"];
export function CreatorOnboarding() {
  const [step, setStep] = useState(0); const [done, setDone] = useState(false);
  if (done) return <div className="app-content"><section className="surface onboarding-success"><CheckCircle weight="fill" /><h1>Your profile is ready for review.</h1><p>PRIFYN will only use connected or submitted evidence. You can update availability and rate preferences at any time.</p><a className="button button-dark" href="/creator/profile">View my profile</a></section></div>;
  return <div className="app-content"><header className="app-page-head"><div><span>Creator onboarding</span><h1>Build a profile brands can trust.</h1><p>Your evidence stays visible to you. Nothing is auto-published without confirmation.</p></div><span className="completion-ring">{(step + 1) * 20}%</span></header><nav className="onboarding-steps" aria-label="Onboarding progress">{steps.map((item, index) => <button type="button" className={index === step ? "active" : index < step ? "done" : ""} key={item} onClick={() => index <= step && setStep(index)}><b>{index < step ? <Check /> : index + 1}</b><span>{item}</span></button>)}</nav><section className="surface onboarding-panel"><div><span className="section-kicker">Step {step + 1} of {steps.length}</span><h2>{step === 0 ? "Tell brands who you are" : step === 1 ? "Connect your public presence" : step === 2 ? "Show work that represents you" : step === 3 ? "Set collaboration preferences" : "Review before analysis"}</h2><p>{step === 0 ? "This becomes the foundation of your creator identity." : step === 1 ? "Use public links now. Approved API connections can be added later." : step === 2 ? "Links are enough; uploads can be added when object storage is connected." : step === 3 ? "These preferences help PRIFYN avoid irrelevant opportunities." : "AI analysis shows evidence, confidence, and limitations. You stay in control."}</p></div><form onSubmit={event => { event.preventDefault(); if (step < 4) setStep(step + 1); else setDone(true); }}>
      {step === 0 && <div className="workflow-form-grid"><label className="field"><span>Display name</span><input required defaultValue="Nabila Putri" /></label><label className="field"><span>Location</span><input required defaultValue="Jakarta" /></label><label className="field field-wide"><span>Bio</span><textarea required defaultValue="Food creator sharing honest, practical stories for modern Indonesian families." /></label><label className="field"><span>Languages</span><input defaultValue="Bahasa Indonesia, English" /></label><label className="field"><span>Primary niches</span><input defaultValue="Food, Lifestyle, FMCG" /></label></div>}
      {step === 1 && <div className="social-connect-list">{["TikTok", "Instagram", "YouTube", "Lemon8", "Website"].map((item, index) => <label key={item}><b>{item.slice(0, 2).toUpperCase()}</b><span><strong>{item}</strong><small>{index < 2 ? "Public profile found" : "Optional"}</small></span><input aria-label={`${item} URL`} defaultValue={index === 0 ? "https://tiktok.com/@nabilaeats" : index === 1 ? "https://instagram.com/nabilaeats" : ""} placeholder="Paste public profile URL" /><LinkSimple /></label>)}</div>}
      {step === 2 && <div className="portfolio-uploader"><UploadSimple weight="duotone" /><h3>Add a link or upload work</h3><p>Videos, images, campaign results, testimonials, and previous brand collaborations.</p><label className="field"><span>Public work URL</span><input type="url" defaultValue="https://tiktok.com/@nabilaeats/video/example" /></label><button className="button button-outline" type="button">Add another item</button></div>}
      {step === 3 && <div className="preference-grid"><fieldset><legend>Preferred collaboration</legend>{["Paid campaign", "Affiliate", "Product seeding", "UGC", "Event"].map((item, index) => <label key={item}><input type="checkbox" defaultChecked={index < 3} />{item}</label>)}</fieldset><div><label className="field"><span>Rate guidance (optional)</span><input defaultValue="Rp8.000.000 – Rp12.000.000" /></label><label className="field"><span>Availability</span><select defaultValue="aug"><option value="now">Available now</option><option value="aug">Available from 18 Aug</option><option value="full">Fully booked</option></select></label></div></div>}
      {step === 4 && <div className="review-consent"><Sparkle weight="duotone" /><div><h3>Evidence-led analysis</h3><p>PRIFYN may analyze the portfolio and public links you provided for content style, brand safety, audience fit, and campaign readiness. Every score includes a reason and confidence level.</p><label><input type="checkbox" required /> I understand and consent to this analysis.</label></div></div>}
      <footer className="onboarding-actions"><button className="button button-outline" disabled={step === 0} type="button" onClick={() => setStep(step - 1)}><ArrowLeft /> Back</button><button className="button button-dark" type="submit">{step === 4 ? "Submit profile" : "Continue"} <ArrowRight /></button></footer>
    </form></section></div>;
}
