"use client";

import Link from "next/link";
import { useState } from "react";
import type { ReactNode } from "react";
import { ArrowLeft, CalendarCheck, ChartLineUp, CheckCircle, ClockCounterClockwise, Info, PaperPlaneTilt, SealCheck, ShieldCheck, Sparkle, Star, TrendUp, X } from "@phosphor-icons/react";
import type { CreatorProfile } from "@/lib/creator-intelligence-data";

const tabs = ["Overview", "Portfolio", "Audience", "Performance", "Reviews", "History"];

export function CreatorProfileView({ creator }: { creator: CreatorProfile }) {
  const [tab, setTab] = useState("Overview");
  const [evidence, setEvidence] = useState<string | null>(null);
  const [inviting, setInviting] = useState(false);
  const [shortlisted, setShortlisted] = useState(false);
  const [invited, setInvited] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 2500); };
  return <div className="app-content creator-profile-page">
    <Link className="back-link" href="/app/creators"><ArrowLeft /> Creator discovery</Link>
    <header className="profile-hero surface"><div className="profile-identity"><span className="creator-avatar large">{creator.initials}</span><div><span className="profile-eyebrow">{creator.verification} <SealCheck weight="fill" /></span><h1>{creator.name}</h1><p>{creator.handle} · {creator.location} · {creator.languages.join(" / ")}</p><div className="creator-tags">{creator.niches.map(item => <span key={item}>{item}</span>)}</div></div></div><div className="profile-actions"><button className={`button ${shortlisted ? "button-soft" : "button-outline"}`} type="button" onClick={() => { setShortlisted(value => !value); notify(shortlisted ? "Creator removed from the shortlist." : "Creator saved to your Ramadan shortlist."); }}><CheckCircle weight={shortlisted ? "fill" : "regular"} /> {shortlisted ? "Shortlisted" : "Shortlist"}</button><button className="button button-dark" type="button" onClick={() => invited ? notify("Invitation is already in Talent Pipeline.") : setInviting(true)}><PaperPlaneTilt /> {invited ? "Invitation sent" : "Invite to campaign"}</button></div></header>
    <nav className="page-tabs profile-tabs" aria-label="Creator profile sections">{tabs.map(item => <button key={item} className={tab === item ? "active" : ""} type="button" onClick={() => setTab(item)}>{item}</button>)}</nav>
    {tab === "Overview" ? <div className="profile-layout"><div className="profile-main">
      <section className="surface ai-summary-card"><div className="surface-head"><h2><Sparkle weight="fill" /> AI creator summary</h2><span className="confidence-chip">94% confidence</span></div><div className="ai-summary-body"><p>{creator.summary}</p><div><span>Strong for</span>{creator.strengths.map(item => <b key={item}><CheckCircle weight="fill" />{item}</b>)}</div><aside><Info weight="fill" /><span><strong>Potential risk</strong>{creator.risk}</span></aside></div></section>
      <section className="surface scorecard"><div className="surface-head"><h2>Explainable scorecard</h2><span>Analysis updated 2 Aug 2026</span></div>{creator.scores.map(score => <button type="button" className="score-row" key={score.label} onClick={() => setEvidence(score.label)}><span>{score.label}</span><i><b style={{ width: `${score.score}%` }} /></i><strong>{score.score}</strong><small>{score.reason}</small><em>Evidence →</em></button>)}</section>
      <section className="surface portfolio-preview"><div className="surface-head"><h2>Selected work</h2><button type="button" onClick={() => setTab("Portfolio")}>View all</button></div><div className="portfolio-grid">{["Fast meal, real reaction", "One-pan weeknight story", "Market-to-table series"].map((item, index) => <article key={item}><div className={`portfolio-art art-${index + 1}`}><span>0:{18 + index * 7}</span></div><strong>{item}</strong><small>{index === 0 ? "212K views · 7.4% ER" : index === 1 ? "148K views · 6.9% ER" : "96K views · 8.1% ER"}</small></article>)}</div></section>
    </div><aside className="profile-side"><section className="surface fit-panel"><span>Campaign match</span><strong>{creator.fit}%</strong><p>Ramadan Made Simple</p><button type="button" onClick={() => setEvidence("Campaign match")}>Why this score</button></section><section className="surface quick-facts"><h2>Decision facts</h2><div><ChartLineUp /><span><small>Audience</small><b>{creator.followers} followers</b></span></div><div><Sparkle /><span><small>Average views</small><b>{creator.averageViews}</b></span></div><div><CalendarCheck /><span><small>Availability</small><b>{creator.availability}</b></span></div><div><ShieldCheck /><span><small>Rate guidance</small><b>{creator.rate}</b></span></div></section></aside></div> : <ProfileTab tab={tab} creator={creator} onEvidence={setEvidence} />}
    {evidence && <div className="dialog-backdrop" role="presentation" onMouseDown={() => setEvidence(null)}><section className="dialog-card evidence-dialog" role="dialog" aria-modal="true" aria-labelledby="evidence-title" onMouseDown={event => event.stopPropagation()}><button className="dialog-close" type="button" aria-label="Close" onClick={() => setEvidence(null)}><X /></button><span className="section-kicker">Decision evidence</span><h2 id="evidence-title">{evidence}</h2><div className="evidence-ledger"><article><CheckCircle weight="fill" /><div><strong>Public content analysis</strong><p>48 recent posts reviewed; data observed 2 Aug 2026.</p></div></article><article><CheckCircle weight="fill" /><div><strong>Campaign history</strong><p>Four approved collaborations; median delivery was one day early.</p></div></article><article><Info weight="fill" /><div><strong>Limitation</strong><p>Audience demographics are platform-reported and may change between snapshots.</p></div></article></div><p className="confidence-note">Confidence is based on evidence freshness, coverage, and agreement between sources.</p></section></div>}
    {inviting && <div className="dialog-backdrop" role="presentation" onMouseDown={() => setInviting(false)}><section className="dialog-card" role="dialog" aria-modal="true" aria-labelledby="invite-title" onMouseDown={event => event.stopPropagation()}><button className="dialog-close" type="button" aria-label="Close" onClick={() => setInviting(false)}><X /></button><span className="section-kicker">Campaign invitation</span><h2 id="invite-title">Invite {creator.name}</h2><form className="dialog-form" onSubmit={event => { event.preventDefault(); setInviting(false); setInvited(true); notify("Invitation sent and added to Talent Pipeline."); }}><label className="field"><span>Campaign</span><select><option>Ramadan Made Simple</option><option>Weekday Lunch Reset</option></select></label><label className="field"><span>Personal message</span><textarea defaultValue={`Hi ${creator.name.split(" ")[0]}, your storytelling and audience fit look strong for this campaign.`} /></label><div className="dialog-actions"><button type="button" className="button button-outline" onClick={() => setInviting(false)}>Cancel</button><button className="button button-dark" type="submit">Send invitation</button></div></form></section></div>}
    {notice && <div className="toast" role="status"><CheckCircle weight="fill" />{notice}</div>}
  </div>;
}

function ProfileTab({ tab, creator, onEvidence }: { tab: string; creator: CreatorProfile; onEvidence: (value: string) => void }) {
  if (tab === "Portfolio") return <section className="profile-detail-grid"><div className="surface profile-detail-main"><div className="surface-head"><div><h2>Campaign-ready portfolio</h2><span>Public links and verified result snapshots</span></div><span className="status-pill"><CheckCircle weight="fill" /> 3 verified</span></div><div className="portfolio-grid expanded">{["Fast meal, real reaction", "One-pan weeknight story", "Market-to-table series", "Kitchen reset UGC", "Family taste test", "Ramadan prep guide"].map((item, index) => <article key={item}><div className={`portfolio-art art-${index % 3 + 1}`}><span>0:{18 + index * 5}</span></div><strong>{item}</strong><small>{92 + index * 24}K views · {(6.1 + index * .3).toFixed(1)}% ER</small></article>)}</div></div><aside className="surface profile-detail-side"><h2>Portfolio evidence</h2><Fact icon={<CheckCircle />} label="Brand work" value="4 collaborations verified" /><Fact icon={<ShieldCheck />} label="Usage rights" value="Confirm per deliverable" /><Fact icon={<ClockCounterClockwise />} label="Freshness" value="Updated 3 days ago" /></aside></section>;
  if (tab === "Audience") return <section className="profile-detail-grid"><div className="surface profile-detail-main padded"><div className="surface-head"><div><h2>Audience composition</h2><span>Platform-reported snapshot · 2 Aug 2026</span></div><button onClick={() => onEvidence("Audience quality")}>View source evidence</button></div><div className="audience-kpis"><Metric label="Indonesia" value="86%" /><Metric label="Jakarta metro" value="42%" /><Metric label="Age 24–34" value="58%" /><Metric label="Women" value="67%" /></div><Breakdown title="Top locations" items={[["Jakarta",42],["Bandung",14],["Surabaya",11],["Other",33]]} /><Breakdown title="Audience age" items={[["18–24",22],["25–34",58],["35–44",16],["45+",4]]} /></div><aside className="surface profile-detail-side"><h2>Audience decision</h2><div className="detail-score">88<small>/100 quality</small></div><p>Location and engagement patterns align with the campaign target. Connect a first-party export before high-spend activation.</p><span className="confidence-chip">84% confidence</span></aside></section>;
  if (tab === "Performance") return <section className="surface profile-detail-main padded"><div className="surface-head"><div><h2>Performance track record</h2><span>Only attributed or brand-verified outcomes</span></div><span className="status-pill"><TrendUp /> Above benchmark</span></div><div className="audience-kpis performance"><Metric label="Median views" value={creator.averageViews} /><Metric label="Engagement" value={creator.engagement} /><Metric label="On-time delivery" value="100%" /><Metric label="Historic ROAS" value="4.6×" /></div><div className="profile-table"><div className="profile-table-row heading"><span>Campaign</span><span>Objective</span><span>Views</span><span>Result</span><span>Status</span></div>{[["Sambal Weeknight", "Sales", "212K", "4.8× ROAS"],["Family Table", "Engagement", "148K", "7.1% ER"],["Market Stories", "Awareness", "96K", "+31% reach"]].map(row => <div className="profile-table-row" key={row[0]}>{row.map(value => <span key={value}>{value}</span>)}<b>Verified</b></div>)}</div></section>;
  if (tab === "Reviews") return <section className="profile-detail-grid"><div className="surface profile-detail-main padded"><div className="surface-head"><div><h2>Brand reviews</h2><span>Structured feedback from completed collaborations</span></div><strong className="review-score"><Star weight="fill" /> 4.8 / 5</strong></div>{[["Nusa Spice", "Clear communicator and delivered one day early. Product integration felt natural.", "5.0"],["Dapur Saji", "Strong first draft. Needed one small CTA revision before approval.", "4.7"],["Pasar Kita", "Professional on set and transparent about production timing.", "4.8"]].map(([brand, quote, score]) => <article className="brand-review" key={brand}><span>{brand.slice(0,2).toUpperCase()}</span><div><strong>{brand}</strong><p>{quote}</p><small>Verified collaboration · Communication, delivery, professionalism</small></div><b><Star weight="fill" />{score}</b></article>)}</div><aside className="surface profile-detail-side"><h2>Review dimensions</h2><Breakdown title="Team feedback" items={[["Communication",96],["Professionalism",94],["Delivery",97],["Revision handling",91]]} /></aside></section>;
  return <section className="surface profile-detail-main padded"><div className="surface-head"><div><h2>Campaign history</h2><span>Invitation-to-payment audit trail</span></div><span className="status-pill"><ClockCounterClockwise /> Complete trail</span></div><div className="history-timeline">{[["2 Aug 2026", "Portfolio evidence refreshed", "48 public posts analyzed; confidence recalculated."],["18 Jul 2026", "Nusa Spice payment released", "Deliverable approved and payment status marked paid."],["14 Jul 2026", "Final video approved", "One CTA revision completed within the agreed cap."],["4 Jul 2026", "Campaign invitation accepted", "Rate and availability confirmed by creator."],["12 May 2026", "Identity manually verified", "Government ID and social ownership reviewed."]].map(([date,title,detail], index) => <article key={title}><i className={index === 0 ? "current" : ""} /><time>{date}</time><div><strong>{title}</strong><p>{detail}</p></div></article>)}</div></section>;
}

function Fact({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="profile-fact-icon">{icon}<span><small>{label}</small><b>{value}</b></span></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function Breakdown({ title, items }: { title: string; items: (string | number)[][] }) { return <div className="profile-breakdown"><strong>{title}</strong>{items.map(([label,value]) => <div key={label}><span>{label}</span><i><b style={{ width: `${value}%` }} /></i><em>{value}%</em></div>)}</div>; }
