"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, CalendarCheck, ChartLineUp, CheckCircle, Info, PaperPlaneTilt, SealCheck, ShieldCheck, Sparkle, X } from "@phosphor-icons/react";
import type { CreatorProfile } from "@/lib/creator-intelligence-data";

const tabs = ["Overview", "Portfolio", "Audience", "Performance", "Reviews", "History"];

export function CreatorProfileView({ creator }: { creator: CreatorProfile }) {
  const [tab, setTab] = useState("Overview");
  const [evidence, setEvidence] = useState<string | null>(null);
  const [inviting, setInviting] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 2500); };
  return <div className="app-content creator-profile-page">
    <Link className="back-link" href="/app/creators"><ArrowLeft /> Creator discovery</Link>
    <header className="profile-hero surface"><div className="profile-identity"><span className="creator-avatar large">{creator.initials}</span><div><span className="profile-eyebrow">{creator.verification} <SealCheck weight="fill" /></span><h1>{creator.name}</h1><p>{creator.handle} · {creator.location} · {creator.languages.join(" / ")}</p><div className="creator-tags">{creator.niches.map(item => <span key={item}>{item}</span>)}</div></div></div><div className="profile-actions"><button className="button button-outline" type="button" onClick={() => notify("Creator saved to your Ramadan shortlist.")}><CheckCircle /> Shortlist</button><button className="button button-dark" type="button" onClick={() => setInviting(true)}><PaperPlaneTilt /> Invite to campaign</button></div></header>
    <nav className="page-tabs profile-tabs" aria-label="Creator profile sections">{tabs.map(item => <button key={item} className={tab === item ? "active" : ""} type="button" onClick={() => setTab(item)}>{item}</button>)}</nav>
    {tab === "Overview" ? <div className="profile-layout"><div className="profile-main">
      <section className="surface ai-summary-card"><div className="surface-head"><h2><Sparkle weight="fill" /> AI creator summary</h2><span className="confidence-chip">94% confidence</span></div><div className="ai-summary-body"><p>{creator.summary}</p><div><span>Strong for</span>{creator.strengths.map(item => <b key={item}><CheckCircle weight="fill" />{item}</b>)}</div><aside><Info weight="fill" /><span><strong>Potential risk</strong>{creator.risk}</span></aside></div></section>
      <section className="surface scorecard"><div className="surface-head"><h2>Explainable scorecard</h2><span>Analysis updated 2 Aug 2026</span></div>{creator.scores.map(score => <button type="button" className="score-row" key={score.label} onClick={() => setEvidence(score.label)}><span>{score.label}</span><i><b style={{ width: `${score.score}%` }} /></i><strong>{score.score}</strong><small>{score.reason}</small><em>Evidence →</em></button>)}</section>
      <section className="surface portfolio-preview"><div className="surface-head"><h2>Selected work</h2><button type="button" onClick={() => setTab("Portfolio")}>View all</button></div><div className="portfolio-grid">{["Fast meal, real reaction", "One-pan weeknight story", "Market-to-table series"].map((item, index) => <article key={item}><div className={`portfolio-art art-${index + 1}`}><span>0:{18 + index * 7}</span></div><strong>{item}</strong><small>{index === 0 ? "212K views · 7.4% ER" : index === 1 ? "148K views · 6.9% ER" : "96K views · 8.1% ER"}</small></article>)}</div></section>
    </div><aside className="profile-side"><section className="surface fit-panel"><span>Campaign match</span><strong>{creator.fit}%</strong><p>Ramadan Made Simple</p><button type="button" onClick={() => setEvidence("Campaign match")}>Why this score</button></section><section className="surface quick-facts"><h2>Decision facts</h2><div><ChartLineUp /><span><small>Audience</small><b>{creator.followers} followers</b></span></div><div><Sparkle /><span><small>Average views</small><b>{creator.averageViews}</b></span></div><div><CalendarCheck /><span><small>Availability</small><b>{creator.availability}</b></span></div><div><ShieldCheck /><span><small>Rate guidance</small><b>{creator.rate}</b></span></div></section></aside></div> : <section className="surface profile-placeholder"><Sparkle weight="duotone" /><h2>{tab}</h2><p>{tab === "Portfolio" ? "Campaign work, public social links, testimonials, and verified result snapshots live here." : tab === "Audience" ? "Audience location, age, gender, quality, and source freshness are shown with consent and provenance." : tab === "Performance" ? "Campaign outcomes, delivery reliability, views, clicks, conversions, and ROAS appear after attribution is connected." : tab === "Reviews" ? "Structured brand reviews focus on communication, professionalism, and delivery—not popularity." : "Invitations, applications, collaborations, revisions, and payouts form a complete audit trail."}</p><button className="button button-outline" type="button" onClick={() => setTab("Overview")}>Back to overview</button></section>}
    {evidence && <div className="dialog-backdrop" role="presentation" onMouseDown={() => setEvidence(null)}><section className="dialog-card evidence-dialog" role="dialog" aria-modal="true" aria-labelledby="evidence-title" onMouseDown={event => event.stopPropagation()}><button className="dialog-close" type="button" aria-label="Close" onClick={() => setEvidence(null)}><X /></button><span className="section-kicker">Decision evidence</span><h2 id="evidence-title">{evidence}</h2><div className="evidence-ledger"><article><CheckCircle weight="fill" /><div><strong>Public content analysis</strong><p>48 recent posts reviewed; data observed 2 Aug 2026.</p></div></article><article><CheckCircle weight="fill" /><div><strong>Campaign history</strong><p>Four approved collaborations; median delivery was one day early.</p></div></article><article><Info weight="fill" /><div><strong>Limitation</strong><p>Audience demographics are platform-reported and may change between snapshots.</p></div></article></div><p className="confidence-note">Confidence is based on evidence freshness, coverage, and agreement between sources.</p></section></div>}
    {inviting && <div className="dialog-backdrop" role="presentation" onMouseDown={() => setInviting(false)}><section className="dialog-card" role="dialog" aria-modal="true" aria-labelledby="invite-title" onMouseDown={event => event.stopPropagation()}><button className="dialog-close" type="button" aria-label="Close" onClick={() => setInviting(false)}><X /></button><span className="section-kicker">Campaign invitation</span><h2 id="invite-title">Invite {creator.name}</h2><form className="dialog-form" onSubmit={event => { event.preventDefault(); setInviting(false); notify("Invitation sent and added to Talent Pipeline."); }}><label className="field"><span>Campaign</span><select><option>Ramadan Made Simple</option><option>Weekday Lunch Reset</option></select></label><label className="field"><span>Personal message</span><textarea defaultValue={`Hi ${creator.name.split(" ")[0]}, your storytelling and audience fit look strong for this campaign.`} /></label><div className="dialog-actions"><button type="button" className="button button-outline" onClick={() => setInviting(false)}>Cancel</button><button className="button button-dark" type="submit">Send invitation</button></div></form></section></div>}
    {notice && <div className="toast" role="status"><CheckCircle weight="fill" />{notice}</div>}
  </div>;
}
