"use client";

import { FormEvent, useState } from "react";
import { ArrowRight, CalendarCheck, Check, CheckCircle, FilmSlate, LockSimple, MagnifyingGlass, Star, UsersThree } from "@phosphor-icons/react";

const levels = ["Mega", "Macro", "Micro", "Nano", "Buzzer Package"];
const platforms = ["TikTok", "Meta", "Google", "LinkedIn", "Tokopedia", "Shopee"];
const candidates = [
  { name: "Nabila Putri", handle: "@nabilaeats", level: "Micro", platform: "TikTok · Instagram", fit: 87, rate: "Rp 4.5m", roas: "4.6×" },
  { name: "Ardian Prakoso", handle: "@ardianfamily", level: "Macro", platform: "Instagram · YouTube", fit: 81, rate: "Rp 8.2m", roas: "4.1×" },
  { name: "Dimas Wibowo", handle: "@dimastries", level: "Nano", platform: "TikTok", fit: 76, rate: "Rp 2.1m", roas: "2.2×" },
];

export function KolWindow() {
  const [stage, setStage] = useState<"input" | "execution" | "post">("input");
  const [selected, setSelected] = useState(["Nabila Putri"]);
  const [saved, setSaved] = useState(false);
  const [submissionStatus, setSubmissionStatus] = useState<"Submitted" | "Revision 1/3" | "Approved" | "Scheduled">("Submitted");

  function saveBrief(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaved(true); setStage("execution"); }
  function toggleCreator(name: string) { setSelected(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name]); }

  return <div className="app-content workflow-page"><header className="app-page-head"><div><span>Influencer marketing workspace</span><h1>KOL Campaigns</h1><p>Find the right creators, manage content approvals, and measure campaign impact.</p></div><span className={`workflow-health ${submissionStatus === "Scheduled" ? "live" : ""}`}><i />{submissionStatus === "Scheduled" ? "Publish scheduled" : saved ? `${selected.length} KOL selected` : "Draft brief"}</span></header><KolSteps active={stage} saved={saved} scheduled={submissionStatus === "Scheduled"} onChange={setStage} />

    {stage === "input" && <form onSubmit={saveBrief} className="workflow-grid kol-input-grid"><section className="surface workflow-card"><div className="workflow-card-head"><span><UsersThree weight="duotone" /></span><div><small>01 · Campaign input</small><h2>Shape the KOL brief</h2></div></div><div className="workflow-form-grid"><label className="field"><span>Campaign name</span><input required defaultValue="Ramadan Made Simple" /></label><label className="field"><span>Campaign objective</span><select defaultValue="Sales / Order"><option>Awareness</option><option>Traffic</option><option>Engagement</option><option>Leads</option><option>Sales / Order</option></select></label><fieldset className="field field-wide platform-picker"><legend>KOL level</legend>{levels.map(level => <label key={level}><input type="checkbox" defaultChecked={level === "Micro" || level === "Nano"} /><span>{level}</span></label>)}</fieldset><label className="field field-wide"><span>Detail brief</span><textarea required defaultValue="Show how Nusa Spice makes family iftar preparation easier. Content must feel practical, warm, and locally relevant. Include one preparation moment and a clear product result." /></label><fieldset className="field field-wide platform-picker"><legend>Platforms</legend>{platforms.map(platform => <label key={platform}><input type="checkbox" defaultChecked={platform === "TikTok" || platform === "Meta"} /><span>{platform}</span></label>)}</fieldset></div></section><section className="surface workflow-card"><div className="workflow-card-head"><span><Star weight="duotone" /></span><div><small>02 · Success criteria</small><h2>Make the expected result explicit</h2></div></div><div className="workflow-form-grid"><label className="field"><span>Primary KPI</span><select defaultValue="Conversions"><option>Views</option><option>Clicks</option><option>Conversions</option></select></label><label className="field"><span>KPI target</span><input required type="number" defaultValue="1200" /></label><label className="field"><span>Total budget</span><input required type="number" defaultValue="28000000" /></label><label className="field"><span>Maximum revisions</span><select defaultValue="3"><option>1</option><option>2</option><option>3</option></select></label><label className="field"><span>Start date</span><input required type="date" defaultValue="2026-08-10" /></label><label className="field"><span>End date</span><input required type="date" defaultValue="2026-08-30" /></label></div><div className="brief-note"><CheckCircle weight="fill" /><span>The MVP uses PRIFYN&apos;s curated KOL database. External sourcing connectors can be added after the workflow is validated.</span></div><button className="button button-dark workflow-submit" type="submit">Save brief and shortlist <ArrowRight /></button></section></form>}

    {stage === "execution" && <div className="workflow-stack"><section className="surface workflow-card"><div className="workflow-card-head"><span><MagnifyingGlass weight="duotone" /></span><div><small>KOL list and profile</small><h2>Select with evidence, not follower count alone</h2></div></div><div className="kol-candidates">{candidates.map(candidate => <article key={candidate.name} className={selected.includes(candidate.name) ? "selected" : ""}><div className="kol-avatar">{candidate.name.split(" ").map(part => part[0]).join("")}</div><div><strong>{candidate.name}</strong><span>{candidate.handle} · {candidate.level}</span><small>{candidate.platform}</small></div><div className="kol-fit"><b>{candidate.fit}%</b><span>campaign fit</span></div><div><strong>{candidate.rate}</strong><small>rate card · {candidate.roas} hist. ROAS</small></div><button type="button" className={`button ${selected.includes(candidate.name) ? "button-outline" : "button-dark"}`} onClick={() => toggleCreator(candidate.name)}>{selected.includes(candidate.name) ? "Selected" : "Select"}</button></article>)}</div></section><section className="surface workflow-card"><div className="workflow-card-head"><span><FilmSlate weight="duotone" /></span><div><small>Submission workflow</small><h2>Review, revise, and approve</h2></div></div><div className="submission-flow"><div><span>Video submission</span><strong>Nabila · TikTok draft v1</strong><small>Submitted 2 hours ago</small></div><ArrowRight /><div><span>Review status</span><strong>{submissionStatus}</strong><small>Revision cap: 3 rounds</small></div><ArrowRight /><div><span>Publish</span><strong>{submissionStatus === "Scheduled" ? "16 Aug · 19:00 WIB" : "Waiting for approval"}</strong><small>Manual confirmation fallback available</small></div></div><div className="workflow-actions"><button type="button" className="button button-outline" disabled={submissionStatus === "Approved" || submissionStatus === "Scheduled"} onClick={() => setSubmissionStatus("Revision 1/3")}>Request revision</button><button type="button" className="button button-dark" onClick={() => setSubmissionStatus(submissionStatus === "Approved" ? "Scheduled" : "Approved")}><CalendarCheck />{submissionStatus === "Approved" ? "Schedule publish" : submissionStatus === "Scheduled" ? "Scheduled" : "Approve video"}</button></div></section></div>}

    {stage === "post" && <div className="workflow-stack"><section className="surface report-overview"><div className="report-score"><span>KOL campaign ROAS</span><strong>4.18×</strong><small>Rp 57.4m attributed revenue</small></div><div className="metric-grid"><Metric label="Views" value="1.26m" /><Metric label="Clicks" value="48.7k" /><Metric label="Conversions" value="2,140" /><Metric label="KOL cost" value="Rp 13.7m" /></div></section><section className="surface table-wrap"><div className="surface-head"><h2>KOL performance report</h2><span className="status-pill"><CheckCircle weight="fill" /> Data current</span></div><table className="data-table"><thead><tr><th>KOL</th><th>Views</th><th>Clicks</th><th>Conversion</th><th>Attributed revenue</th><th>ROAS</th></tr></thead><tbody>{candidates.map((creator, index) => <tr key={creator.name}><td><strong>{creator.name}</strong><small>{creator.handle}</small></td><td>{[486000,392000,184000][index].toLocaleString()}</td><td>{[18420,15280,7860][index].toLocaleString()}</td><td>{[814,702,326][index]}</td><td>{["Rp 21.8m","Rp 19.4m","Rp 7.2m"][index]}</td><td><strong>{creator.roas}</strong></td></tr>)}</tbody></table></section><div className="evidence-strip"><CheckCircle weight="fill" /><span><strong>Decision:</strong> rebook Nabila for the next conversion campaign; retain Dimas for awareness-only briefs.</span><small>High confidence · post-level evidence</small></div></div>}
  </div>;
}

function KolSteps({ active, saved, scheduled, onChange }: { active: "input" | "execution" | "post"; saved: boolean; scheduled: boolean; onChange: (stage: "input" | "execution" | "post") => void }) {
  const steps = [["input", "Brief", "Goal, KOL criteria, KPI"], ["execution", "Collaboration", "Select, review, schedule"], ["post", "Results", "Performance and ROAS"]] as const;
  return <nav className="workflow-steps" aria-label="KOL campaign stages">{steps.map(([key, title, detail], index) => { const locked = key === "execution" ? !saved : key === "post" ? !scheduled : false; const done = key === "input" ? saved : key === "execution" ? scheduled : false; return <button key={key} type="button" disabled={locked} aria-current={active === key ? "step" : undefined} className={`${active === key ? "active" : ""} ${done ? "done" : ""}`} title={locked ? key === "execution" ? "Save the campaign brief first" : "Schedule publishing first" : undefined} onClick={() => onChange(key)}><b>{locked ? <LockSimple /> : done ? <Check /> : index + 1}</b><span><strong>{title}</strong><small>{locked ? key === "execution" ? "Complete brief first" : "Schedule to unlock" : detail}</small></span></button>; })}</nav>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="metric-box"><span>{label}</span><strong>{value}</strong></div>; }
