export const blogPosts = [
  {
    slug: "growth-without-operational-readiness",
    category: "Growth operations",
    market: "Global",
    read: "6 min read",
    title: "Growth without operational readiness is an expensive illusion",
    excerpt: "Why successful campaigns can still hurt a business—and the readiness signals owners should review before scaling demand.",
    date: "4 Aug 2026",
    image: "readiness",
    sections: [
      { heading: "Demand is only half of growth", body: "A campaign can outperform its targets while the business loses margin, disappoints customers, or overwhelms the team. Growth becomes durable only when demand generation and fulfillment readiness are reviewed together." },
      { heading: "Review constraints before increasing spend", body: "The useful question is not simply whether acquisition is working. Ask whether inventory, service capacity, creator delivery, approvals, and cash timing can support the next increase in demand." },
      { heading: "Turn signals into an owned decision", body: "Every weekly review should end with a specific action, an owner, a deadline, and an expected outcome. Otherwise reporting remains information without operational value." },
    ],
  },
  {
    slug: "indonesia-sme-growth-stack",
    category: "Indonesia market",
    market: "Indonesia",
    read: "8 min read",
    title: "The Indonesian growth stack is WhatsApp, marketplaces, creators, and spreadsheets",
    excerpt: "Why PRIFYN needs to start from messy reality: Shopee/Tokopedia exports, TikTok creators, WhatsApp leads, and owner-led decisions.",
    date: "12 Aug 2026",
    image: "indonesia-stack",
    sections: [
      { heading: "The operating system is informal", body: "Many Indonesian businesses do not start with a clean CRM or warehouse. They start with marketplace dashboards, WhatsApp follow-ups, creator screenshots, and spreadsheets that only the owner understands." },
      { heading: "Manual data is not a weakness", body: "In this market, exported reports and simple lead sheets can be the fastest way to deliver value before every official integration is approved. The product should make this path feel intentional, not second-class." },
      { heading: "The owner needs a decision, not a model", body: "Recommendations should answer what to do this week: which channel to protect, which creator to invite again, which campaign needs revenue evidence, and which operational bottleneck blocks scaling." },
    ],
  },
  {
    slug: "global-growth-os-lessons",
    category: "Global market",
    market: "Global",
    read: "7 min read",
    title: "What global GTM tools get right—and why SMEs still need a Business OS",
    excerpt: "Modern teams use best-in-class point tools, but owners still need one place to understand whether growth is healthy.",
    date: "10 Aug 2026",
    image: "global-grid",
    sections: [
      { heading: "Point tools optimize local work", body: "Ad platforms optimize delivery, analytics tools explain events, and CRMs track pipeline. The missing layer is the operating decision across all of them." },
      { heading: "SMEs do not have a RevOps department", body: "A larger company can assign analysts to reconcile tools. Smaller businesses need the product itself to translate signals into next actions, confidence, and missing evidence." },
      { heading: "The opportunity is orchestration", body: "A Business OS should not replace every system. It should make the work legible across campaigns, customers, orders, revenue, and operational readiness." },
    ],
  },
  {
    slug: "creator-fit-beyond-followers",
    category: "Creator intelligence",
    market: "Global",
    read: "7 min read",
    title: "Creator fit should never be reduced to follower count",
    excerpt: "A practical model for evaluating content style, audience quality, safety, reliability, and campaign relevance with visible evidence.",
    date: "29 Jul 2026",
    image: "creator-fit",
    sections: [
      { heading: "Reach does not explain relevance", body: "Follower count is useful context, but it cannot explain whether a creator can tell the right story to the right audience in the format a campaign requires." },
      { heading: "Score dimensions separately", body: "Brand safety, storytelling, audience quality, professionalism, and campaign readiness should each show their own reason and confidence. A single unexplained score hides the tradeoffs a reviewer needs." },
      { heading: "Keep the human decision", body: "AI can compress screening work and surface evidence. Selection still belongs to the brand team, especially when context, reputation, and commercial terms are involved." },
    ],
  },
  {
    slug: "marketplace-overselling-indonesia",
    category: "Indonesia market",
    market: "Indonesia",
    read: "6 min read",
    title: "Overselling is not an inventory bug. It is a growth control problem",
    excerpt: "Marketplace sellers can create demand across many accounts faster than they can keep stock, admin, and ratings aligned.",
    date: "27 Jul 2026",
    image: "marketplace",
    sections: [
      { heading: "More accounts means more surface area", body: "Running many marketplace accounts increases the chance of discovery, but it also multiplies the places where stock, campaigns, and customer promises can drift." },
      { heading: "Rating loss is a business cost", body: "When stock is not synchronized, the impact is not only operational. Cancellations, slow handling, and bad reviews reduce future conversion and make paid traffic less efficient." },
      { heading: "Start with stock truth", body: "The first useful system does not need to automate everything. It needs to show which products, accounts, and campaigns are safe to push today." },
    ],
  },
  {
    slug: "kol-roas-without-perfect-apis",
    category: "KOL operations",
    market: "Indonesia",
    read: "5 min read",
    title: "How to measure KOL results before every API is approved",
    excerpt: "Affiliate links, coupon codes, proof screenshots, and order exports can already tell a useful performance story.",
    date: "24 Jul 2026",
    image: "kol",
    sections: [
      { heading: "Perfect attribution can wait", body: "Brands do not need warehouse-grade attribution to learn whether a creator is worth reinviting. They need a consistent way to connect creator content to clicks, leads, coupons, orders, and revenue evidence." },
      { heading: "Every creator needs a tracking path", body: "A campaign should assign a link, coupon, landing page, WhatsApp path, or proof requirement before publishing. Otherwise the result review becomes guesswork." },
      { heading: "Compare efficiency, not vanity", body: "A creator with lower reach can still create more customers. PRIFYN should help teams move budget toward creators who produce business outcomes, not only views." },
    ],
  },
  {
    slug: "weekly-growth-review",
    category: "Operating rhythm",
    market: "Global",
    read: "5 min read",
    title: "A weekly growth review should end with fewer charts and better decisions",
    excerpt: "A 15-minute review format that connects performance movement, evidence, risk, and accountable next actions.",
    date: "22 Jul 2026",
    image: "weekly-review",
    sections: [
      { heading: "Start with changed signals", body: "Review only material changes: performance shifts, approaching constraints, missed deadlines, and new evidence that could change an existing decision." },
      { heading: "Separate diagnosis from action", body: "First agree on what changed and why. Then decide what to do, who owns it, and when the result will be reviewed." },
      { heading: "Record confidence and limitations", body: "A recommendation should say what data supports it, how fresh that data is, and what remains unknown. This prevents certainty from being manufactured by presentation." },
    ],
  },
  {
    slug: "ai-recommendations-need-evidence",
    category: "AI product",
    market: "Global",
    read: "6 min read",
    title: "AI recommendations are only useful when they explain their evidence",
    excerpt: "A black-box growth recommendation creates work. An explainable recommendation creates trust and a better decision.",
    date: "18 Jul 2026",
    image: "ai-evidence",
    sections: [
      { heading: "Confidence should be visible", body: "If data is missing, stale, or incomplete, the answer should say so. The safest AI behavior is not sounding smart; it is knowing when not to overclaim." },
      { heading: "Evidence changes the conversation", body: "When a recommendation cites the campaign, creator, channel, metric, and missing data, the team can debate the decision instead of debating whether the model hallucinated." },
      { heading: "Action is the product", body: "The output should end with what to do next, who should own it, and what result would validate the recommendation." },
    ],
  },
] as const;

export const caseStudies = [
  {
    slug: "restaurant-campaign-readiness",
    industry: "Restaurant · Indonesia",
    label: "Interview-based operating study",
    title: "When a hidden-gem restaurant wins demand before the kitchen is ready",
    summary: "Based on a Rangkum interview with the owner of a small Japanese hidden-gem restaurant. Creator barter worked, but stock, waste, staffing, and channel reporting were still handled manually.",
    challenge: "Creator barter on TikTok and Instagram created strong demand at very low marketing cost, but the owner still had to manage cooking, stock, waste, quality, and channel sales manually. When demand spiked, the business had no shared readiness view to decide whether to push growth or protect operations.",
    decision: "Treat creator demand, kitchen capacity, stock freshness, and channel profitability as one operating review. Before inviting more creators, PRIFYN would ask which service windows can absorb demand, which ingredients are at risk of waste, and which sales channels actually protect margin.",
    outcome: [
      "Creator activity connected to kitchen readiness",
      "Daily stock and waste reminders become part of the growth review",
      "Dine-in, delivery, and marketplace sales can be compared by margin impact",
      "Expansion decisions wait until staffing and operating rhythm are measurable",
    ],
    metrics: [["Rp50–100k", "estimated food cost per creator barter"], ["60–70%", "gross margin range discussed"], ["4 channels", "Grab, GoFood, Shopee, dine-in tracked manually"]],
    sourceUrl: "https://rangkum.rakhaviantoni.com/share/e09adb85575b110aa0f410b7a407d4517989",
    sourceLabel: "Rangkum · Okosan/Kokosan interview",
    image: "restaurant",
  },
  {
    slug: "marketplace-footwear-operations",
    industry: "Marketplace seller · Indonesia",
    label: "Interview-based operating study",
    title: "A footwear seller scales marketplace demand faster than stock can stay true",
    summary: "Based on a Rangkum interview with V Luce, a women’s footwear seller producing through local workshops and selling across Shopee, TikTok, and multiple marketplace accounts.",
    challenge: "The seller expanded from one marketplace account to multiple accounts to increase sales probability, while production, stock, ads, live selling, and admin work stayed constrained. Manual stock tracking caused stockouts, overselling risk, and rating damage.",
    decision: "Make marketplace growth safe before adding more demand. PRIFYN would normalize account-level performance, stock position, ad spend, CPO, live selling capacity, and rating risk into one daily operating view.",
    outcome: [
      "Stock truth shared across marketplace accounts",
      "Ad spend and CPO reviewed against product availability",
      "Live selling and affiliate decisions tied to inventory readiness",
      "Rating risk becomes visible before pushing campaigns",
    ],
    metrics: [["500 pairs", "monthly production per model discussed"], ["10 accounts", "Shopee and Tokopedia accounts used"], ["Rp4–6k", "Shopee CPO range discussed"]],
    sourceUrl: "https://rangkum.rakhaviantoni.com/share/d5b1eb6948218c46e1055618965683cd035b",
    sourceLabel: "Rangkum · V Luce interview",
    image: "footwear",
  },
] as const;
