export const blogPosts = [
  { slug: "growth-without-operational-readiness", category: "Growth operations", read: "6 min read", title: "Growth without operational readiness is an expensive illusion", excerpt: "Why successful campaigns can still hurt a business—and the readiness signals owners should review before scaling demand.", date: "4 Aug 2026", sections: [{ heading: "Demand is only half of growth", body: "A campaign can outperform its targets while the business loses margin, disappoints customers, or overwhelms the team. Growth becomes durable only when demand generation and fulfillment readiness are reviewed together." }, { heading: "Review constraints before increasing spend", body: "The useful question is not simply whether acquisition is working. Ask whether inventory, service capacity, creator delivery, approvals, and cash timing can support the next increase in demand." }, { heading: "Turn signals into an owned decision", body: "Every weekly review should end with a specific action, an owner, a deadline, and an expected outcome. Otherwise reporting remains information without operational value." }] },
  { slug: "creator-fit-beyond-followers", category: "Creator intelligence", read: "7 min read", title: "Creator fit should never be reduced to follower count", excerpt: "A practical model for evaluating content style, audience quality, safety, reliability, and campaign relevance with visible evidence.", date: "29 Jul 2026", sections: [{ heading: "Reach does not explain relevance", body: "Follower count is useful context, but it cannot explain whether a creator can tell the right story to the right audience in the format a campaign requires." }, { heading: "Score dimensions separately", body: "Brand safety, storytelling, audience quality, professionalism, and campaign readiness should each show their own reason and confidence. A single unexplained score hides the tradeoffs a reviewer needs." }, { heading: "Keep the human decision", body: "AI can compress screening work and surface evidence. Selection still belongs to the brand team, especially when context, reputation, and commercial terms are involved." }] },
  { slug: "weekly-growth-review", category: "Operating rhythm", read: "5 min read", title: "A weekly growth review should end with fewer charts and better decisions", excerpt: "A 15-minute review format that connects performance movement, evidence, risk, and accountable next actions.", date: "22 Jul 2026", sections: [{ heading: "Start with changed signals", body: "Review only material changes: performance shifts, approaching constraints, missed deadlines, and new evidence that could change an existing decision." }, { heading: "Separate diagnosis from action", body: "First agree on what changed and why. Then decide what to do, who owns it, and when the result will be reviewed." }, { heading: "Record confidence and limitations", body: "A recommendation should say what data supports it, how fresh that data is, and what remains unknown. This prevents certainty from being manufactured by presentation." }] },
] as const;

export const caseStudies = [
  { slug: "restaurant-campaign-readiness", industry: "Restaurant group", label: "Modeled operating study", title: "Protecting service quality after a creator campaign takes off", summary: "A restaurant team connects creator performance, reservation demand, kitchen capacity, and expiring stock before increasing amplification.", challenge: "A creator campaign created a sharp demand spike, but kitchen capacity and stock visibility remained manual. The marketing team could see engagement while operations saw the risk too late.", decision: "Keep the highest-converting creator content active, reduce paid amplification for seven days, and shift the next activation to lower-load service windows.", outcome: ["One shared readiness review", "Clear owner for capacity action", "Marketing spend tied to service constraints"], metrics: [["24%", "amplification cost increase identified"], ["3", "operational signals connected"], ["7 days", "controlled optimization window"]] },
  { slug: "agency-creator-operations", industry: "Growth agency", label: "Modeled operating study", title: "Replacing creator spreadsheets with an accountable talent pipeline", summary: "An agency standardizes creator screening, invitations, applications, reviews, deliverables, and reporting across client teams.", challenge: "Creator lists, rate negotiations, approvals, and revision history lived in different spreadsheets and chat threads. Client reporting required reconstructing the campaign every month.", decision: "Use one evidence-led talent pipeline, require a reason for every selection decision, and connect approved creators directly to campaign delivery milestones.", outcome: ["Consistent screening criteria", "Visible application ownership", "Reusable executive reporting"], metrics: [["1", "shared recruiting workflow"], ["100%", "selection decisions with reasons"], ["0", "client data mixed across workspaces"]] },
] as const;
