import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle } from "@phosphor-icons/react/dist/ssr";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";

export const metadata: Metadata = { title: "Features", description: "Plan, execute, measure, and improve growth in one connected operating system." };

const features = [
  { eyebrow: "Campaign operations", title: "One accountable campaign workspace.", text: "Move from approved brief to measurable outcome with objectives, budgets, creators, deliverables, submissions, and decisions connected in one timeline.", bullets: ["Outcome-led campaign briefs", "Creator invitations and applications", "Deliverable review and revisions"], cards: [["Campaign readiness", "All launch requirements complete", "Ready to activate"], ["Next deadline", "3 creator drafts due Thursday", "Owner · Maya"], ["Budget coverage", "Rp 42m of Rp 50m allocated", "84% planned"]] },
  { eyebrow: "Creator intelligence", title: "Choose creators for the reason they fit.", text: "Compare channels, content style, audience, brand safety, campaign history, and performance. Every match score includes evidence and limitations.", bullets: ["Explainable campaign matching", "Manual verification workflow", "Portfolio and channel intelligence"], cards: [["Nabila Putri", "87% campaign match", "Food storytelling · High"], ["Ardian Prakoso", "81% campaign match", "Family audience · Strong"], ["Fit explanation", "Audience overlap and historical ROAS", "4 evidence sources"]] },
  { eyebrow: "Measurement & attribution", title: "Connect spend to outcomes without pretending certainty.", text: "Import performance data, define governed metrics, track links and codes, and compare campaigns with visible attribution assumptions and data freshness.", bullets: ["CSV import with validation", "Versioned metric definitions", "Transparent attribution models"], cards: [["Attributed revenue", "Rp 86.4m", "+12.8% week over week"], ["Campaign ROAS", "3.42×", "Last-touch · 7-day window"], ["Data readiness", "86%", "2 creator profiles need refresh"]] },
  { eyebrow: "AI insights", title: "Recommendations with receipts.", text: "PRIFYN diagnoses changes using permission-filtered evidence. The system explains why, states confidence, exposes limitations, and asks a human to decide.", bullets: ["Campaign and creator diagnosis", "Confidence and limitation policy", "Accepted, edited, or dismissed decisions"], cards: [["Diagnosis", "Amplification cost rose 24%", "High confidence"], ["Why", "Conversion held while paid cost increased", "3 sources"], ["Action", "Reduce amplification by 15% for 7 days", "Expected ROAS recovery"]] },
];

export default function FeaturesPage() {
  return <div className="marketing-page"><div className="subpage-header"><MarketingHeader /></div><main><section className="page-hero"><div className="marketing-container"><span className="section-kicker">The Growth OS</span><h1>Every growth signal.<br />One operating rhythm.</h1><p>PRIFYN connects the work your team performs with the outcomes the business needs—so every screen leads to a clear next action.</p><div className="page-hero-actions"><Link className="button button-light button-large" href="/auth/sign-up">Start free <ArrowRight /></Link><Link className="button button-ghost-light button-large" href="/pricing">View pricing</Link></div></div></section><section className="section section-paper"><div className="marketing-container feature-blocks">{features.map((feature, index) => <article className="feature-block" key={feature.title} id={index === 3 ? "trust" : undefined}><div className="feature-block-copy"><span>{feature.eyebrow}</span><h2>{feature.title}</h2><p>{feature.text}</p><div className="feature-list">{feature.bullets.map(item => <span key={item}><CheckCircle weight="fill" />{item}</span>)}</div></div><div className="feature-visual"><div className="visual-stack">{feature.cards.map(([title, value, note], cardIndex) => <div className={`visual-card ${cardIndex === 0 && index === 3 ? "highlight" : ""}`} key={title}><span>{title}</span><strong>{value}</strong><p>{note}</p></div>)}</div></div></article>)}</div></section><section className="final-cta"><div className="marketing-container final-cta-inner"><span className="section-kicker light">Designed for action</span><h2>See what needs attention.<br /><em>Know what to do next.</em></h2><p>Start with a guided Growth OS workspace for your team.</p><Link className="button button-light button-large" href="/auth/sign-up">Create your workspace <ArrowRight /></Link></div></section></main><MarketingFooter /></div>;
}
